In [33]:
import nltk
nltk.download('punkt')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\cof2\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [34]:
from nltk.tokenize import word_tokenize
import pandas as pd
import numpy as np
import re

In [35]:
df = pd.read_csv('../dataset/joined/reviews-outliers-the_story_of_success.csv')

In [36]:
df.shape

(8872, 4)

In [37]:
df.head()

stars                                             review        date  \
0      1  Journalism and pseudoscience. Having read lots...  2017-11-12   
1      5  Salient and grounded. ​Gladwell argues that su...  2018-03-03   
2      3  Interesting enough but certainly no revelation...  2014-06-23   
3      5  Fascinating and thought-provoking. It takes a ...  2019-01-17   
4      3  Enjoyable read but scientifically it makes me ...  2020-02-18   

       country  
0  Reino Unido  
1  Reino Unido  
2  Reino Unido  
3  Reino Unido  
4  Reino Unido

In [38]:
df = df.drop(columns='country')

In [39]:
df

stars                                             review        date
0         1  Journalism and pseudoscience. Having read lots...  2017-11-12
1         5  Salient and grounded. ​Gladwell argues that su...  2018-03-03
2         3  Interesting enough but certainly no revelation...  2014-06-23
3         5  Fascinating and thought-provoking. It takes a ...  2019-01-17
4         3  Enjoyable read but scientifically it makes me ...  2020-02-18
...     ...                                                ...         ...
8867      3  This one is a weird one for me to write, and I...  2021-06-26
8868      5  This has got to be Malcolm Gladwell’s best boo...  2008-12-11
8869      2  This is one of those books that give popular n...  2019-07-21
8870      5  My first exposure to Gladwell. SO was more or ...  2011-07-14
8871      5  This is officially the best book of 2019. Damn...  2019-12-28

[8872 rows x 3 columns]

In [40]:
df['review']

0       Journalism and pseudoscience. Having read lots...
1       Salient and grounded. ​Gladwell argues that su...
2       Interesting enough but certainly no revelation...
3       Fascinating and thought-provoking. It takes a ...
4       Enjoyable read but scientifically it makes me ...
                              ...                        
8867    This one is a weird one for me to write, and I...
8868    This has got to be Malcolm Gladwell’s best boo...
8869    This is one of those books that give popular n...
8870    My first exposure to Gladwell. SO was more or ...
8871    This is officially the best book of 2019. Damn...
Name: review, Length: 8872, dtype: object

In [41]:
# generate text
text_review = df['review']
text_reviews = ''
for i in df['review']:
   text_reviews += str(i)

In [42]:
len(text_reviews)

2195660

### Tokenize

In [ ]:
text = word_tokenize(text_reviews)
print(text)

###  Crreating the Bag of Words using the NLTK. 
### We utilize the Frequency Distribution tool from the NLTK

In [44]:
from nltk.probability import FreqDist 
fdist = FreqDist(text) 
print(fdist.most_common(20))

[('.', 22306), ('the', 13553), (',', 11787), ('and', 11579), ('to', 10346), ('of', 9477), ('a', 8535), ('I', 8139), ('book', 7510), ('is', 5742), ('that', 5084), ('it', 5063), ('in', 4956), ('this', 4000), ('read', 3887), ('!', 3667), ('for', 3025), ('you', 3018), ('Gladwell', 2815), ('success', 2735)]


###  Split the texto into sentences and grouping all in one list called 'dataset'

In [45]:
dataset = nltk.sent_tokenize(text_reviews)

In [46]:
# list of sentences
dataset

['Journalism and pseudoscience.',
 'Having read lots of favourable reviews, I was extremely disappointed.',
 'The book essentially argues against the notion that people are born to succeed.',
 'If you believe that success is a bit more complicated than that, you may be in for a tedious time ahead as it laboriously tries to convince you against something you never thought in the first place.',
 'There is simply not enough here for a book and so the material is stretched out, presenting points that would be common sense to most people seemly expecting the result to be paradigm shifting revelations to the reader.',
 'It circles around the same points approaching from a variety of angles, while ignoring any counter arguments you feel should be addressed.Salient and grounded.',
 '\u200bGladwell argues that success is tightly married to opportunity and time on task.',
 'He states that it takes approximately 10,000 hours to master something and that gives me comfort.',
 'It helps me feel bett

In [ ]:
#preprocessing
for i in range (len(dataset)):
    dataset[i] = dataset[i].lower() #converting all words to lower case
print (dataset)


### Creating a histogram (a list that informs the number of times a word appears in the text)

In [48]:
# creating a histogram

def createHistogram(_dataset):
    word2count = {}
    for data in _dataset:
        words = nltk.word_tokenize(data)
        for word in words:
            if word not in word2count.keys():
                word2count[word] = 1
            else:
                word2count[word] += 1
                
    return word2count

In [49]:
word2count = createHistogram(dataset)

In [50]:
word2count

{'journalism': 10,
 'and': 11746,
 'pseudoscience': 2,
 '.': 22318,
 'having': 147,
 'read': 4241,
 'lots': 118,
 'of': 9514,
 'favourable': 3,
 'reviews': 80,
 ',': 11787,
 'i': 8308,
 'was': 2477,
 'extremely': 90,
 'disappointed': 55,
 'the': 15398,
 'book': 7852,
 'essentially': 25,
 'argues': 35,
 'against': 52,
 'notion': 53,
 'that': 5200,
 'people': 1642,
 'are': 2506,
 'born': 437,
 'to': 10436,
 'succeed': 191,
 'if': 818,
 'you': 3251,
 'believe': 181,
 'success': 2991,
 'is': 5791,
 'a': 9247,
 'bit': 218,
 'more': 1167,
 'complicated': 20,
 'than': 667,
 'may': 322,
 'be': 1869,
 'in': 5243,
 'for': 3168,
 'tedious': 14,
 'time': 896,
 'ahead': 40,
 'as': 2209,
 'it': 6702,
 'laboriously': 3,
 'tries': 29,
 'convince': 16,
 'something': 289,
 'never': 339,
 'thought': 850,
 'first': 431,
 'place': 255,
 'there': 777,
 'simply': 117,
 'not': 2197,
 'enough': 154,
 'here': 136,
 'so': 1195,
 'material': 52,
 'stretched': 8,
 'out': 609,
 'presenting': 18,
 'points': 268,
 'w

### Sorting the list considering the terms that appear in the list more often

In [51]:
import heapq

# sorting the list to check the most frequent words 
freq_words = heapq.nlargest(50,word2count, key=word2count.get)
print (freq_words)

['.', 'the', ',', 'and', 'to', 'of', 'a', 'i', 'book', 'it', 'is', 'this', 'in', 'that', 'read', '!', 'you', 'for', 'success', 'gladwell', 'are', 'was', 'great', 'but', 'on', 'as', 'not', "'s", 'with', 'have', 'my', 'very', 'interesting', 'be', 'his', 'about', 'an', 'how', 'at', 'people', 'what', 'he', 'good', 'one', 'some', 'all', 'outliers', '``', 'or', "n't"]


### Creating the bag of words putting a boolean information for each document saying if each word in the bag of words is in the document or not  

In [52]:
def createBagOfWords(_dataset):
    list = []

    for data in _dataset:
        vector = []
        for word in freq_words:
            if word in nltk.word_tokenize(data):
                vector.append(1) # 1, if word is in document 
            else:
                vector.append(0) # 0, if word is not in document 
        list.append(vector)
        
    bag_of_words = np.asarray(list)
    return bag_of_words

In [53]:
bag = createBagOfWords(dataset)
print(bag)

[[1 0 0 ... 0 0 0]
 [1 0 1 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 1 0 ... 0 0 0]
 [1 1 1 ... 0 0 1]]
